import React, { useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, FileJson2, LockKeyhole, RotateCcw, ShieldCheck } from 'lucide-react';
import { approveSpecGate, createSpecGateArtifact, markSpecGateReady, serializeSpecGate, type SpecGateApprovalChecklist, type SpecGateArtifact, type SpecGateInput } from '../services/specGateService';

const EMPTY: SpecGateInput = { projectName: '', repository: '', problem: '', userOutcome: '', inScope: [], outOfScope: [], constraints: [], acceptanceCriteria: [], clarifications: [], rollbackPlan: '', evidencePaths: [] };
const EXAMPLE: SpecGateInput = {
  projectName: 'Eclipse Library Spec Gate', repository: 'PavelHopson/eclipse-library',
  problem: 'Большая задача может перейти в код до того, как команда согласует границы, риски и проверяемый результат.',
  userOutcome: 'Команда видит одну утверждённую спецификацию до начала реализации.',
  inScope: ['Создать versioned JSON', 'Показать независимый review в Eclipse Chat'],
  outOfScope: ['Автоматический deploy', 'Автономная установка зависимостей'],
  constraints: ['Работать offline', 'Не хранить секреты', 'Сохранить visual contract'],
  acceptanceCriteria: ['JSON проходит строгую проверку', 'Реализация остаётся заблокированной до отдельного разрешения'],
  clarifications: [{ question: 'Кто утверждает реализацию?', answer: 'Участник с правом TASK_APPROVE в Eclipse Chat.' }],
  rollbackPlan: 'Удалить только новый модуль и вернуть прежнюю навигацию без изменения пользовательских данных.',
  evidencePaths: ['src/pages/SpecGate.tsx', 'src/services/specGateService.test.ts'],
};
const EMPTY_CHECKLIST: SpecGateApprovalChecklist = { scopeConfirmed: false, risksConfirmed: false, rollbackConfirmed: false };
const LABELS = { constitution: 'Правила', specify: 'Спецификация', clarify: 'Уточнения', plan: 'План', tasks: 'Задачи', implement: 'Реализация' } as const;
type ListKey = 'inScope' | 'outOfScope' | 'constraints' | 'acceptanceCriteria' | 'evidencePaths' | 'clarifications';
const splitLines = (value: string) => value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean);

function downloadArtifact(artifact: SpecGateArtifact) {
  const url = URL.createObjectURL(new Blob([serializeSpecGate(artifact)], { type: 'application/json' }));
  const anchor = document.createElement('a');
  anchor.href = url; anchor.download = `eclipse-spec-${artifact.id.slice(0, 8)}.json`; anchor.click(); URL.revokeObjectURL(url);
}

function Lines({ label, hint, value, onChange, placeholder }: { label: string; hint: string; value: string; onChange: (value: string) => void; placeholder: string }) {
  return <label className="block text-sm text-gray-300">{label}<span className="ml-2 text-xs text-gray-600">{hint}</span><textarea value={value} onChange={(event) => onChange(event.target.value)} className="hub-input mt-2 min-h-24 resize-y" placeholder={placeholder} /></label>;
}

export const SpecGate: React.FC = () => {
  const [input, setInput] = useState(EMPTY);
  const [lists, setLists] = useState<Record<ListKey, string>>({ inScope: '', outOfScope: '', constraints: '', acceptanceCriteria: '', evidencePaths: '', clarifications: '' });
  const [artifact, setArtifact] = useState<SpecGateArtifact | null>(null);
  const [checklist, setChecklist] = useState(EMPTY_CHECKLIST);
  const [error, setError] = useState('');
  const patch = <K extends keyof SpecGateInput>(key: K, value: SpecGateInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const run = (operation: () => SpecGateArtifact) => { try { setArtifact(operation()); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Не удалось подготовить спецификацию'); } };
  const applyExample = () => { setInput(EXAMPLE); setLists({ inScope: EXAMPLE.inScope.join('\n'), outOfScope: EXAMPLE.outOfScope.join('\n'), constraints: EXAMPLE.constraints.join('\n'), acceptanceCriteria: EXAMPLE.acceptanceCriteria.join('\n'), evidencePaths: EXAMPLE.evidencePaths.join('\n'), clarifications: EXAMPLE.clarifications.map((item) => `${item.question} => ${item.answer}`).join('\n') }); setError(''); };
  const create = () => run(() => createSpecGateArtifact({ ...input, inScope: splitLines(lists.inScope), outOfScope: splitLines(lists.outOfScope), constraints: splitLines(lists.constraints), acceptanceCriteria: splitLines(lists.acceptanceCriteria), evidencePaths: splitLines(lists.evidencePaths), clarifications: splitLines(lists.clarifications).map((item) => { const at = item.indexOf('=>'); return at < 0 ? { question: item, answer: '' } : { question: item.slice(0, at), answer: item.slice(at + 2) }; }) }));
  const reset = () => { if (artifact && !window.confirm('Несохранённая спецификация исчезнет. Начать заново?')) return; setArtifact(null); setChecklist(EMPTY_CHECKLIST); setError(''); };

  return <div className="min-h-full p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 border-b border-hub-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-hub-accent"><ShieldCheck size={15} /> Eclipse Spec Gate</div><h1 className="text-2xl font-bold text-white sm:text-3xl">Сначала договориться. Потом писать код.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-400">Шесть этапов превращают идею в проверяемую спецификацию — локально, без модели, API-ключа и скрытых команд.</p></div><div className="inline-flex w-fit items-center gap-2 rounded-lg border border-amber-400/25 bg-amber-400/5 px-3 py-2 text-xs text-amber-200"><LockKeyhole size={14} /> /implement требует отдельного review</div></header>
    {!artifact ? <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
      <section className="hub-card eclipse-card p-5 sm:p-6"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-white">1. Опишите результат простыми словами</h2><p className="mt-1 text-xs text-gray-500">Не вставляйте ключи, персональные данные и production-конфигурацию.</p></div><button type="button" onClick={applyExample} className="hub-btn-ghost min-h-11 !px-3 !py-2 text-xs">Заполнить пример</button></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-gray-300">Название проекта<input value={input.projectName} onChange={(event) => patch('projectName', event.target.value)} className="hub-input mt-2" placeholder="Eclipse Library" /></label><label className="text-sm text-gray-300">GitHub repository<input value={input.repository} onChange={(event) => patch('repository', event.target.value)} className="hub-input mt-2" placeholder="owner/repository" /></label></div>
        <label className="mt-4 block text-sm text-gray-300">Проблема<textarea value={input.problem} onChange={(event) => patch('problem', event.target.value)} className="hub-input mt-2 min-h-24 resize-y" placeholder="Что сейчас ломается, тормозит или остаётся непонятным?" /></label>
        <label className="mt-4 block text-sm text-gray-300">Пользовательский результат<input value={input.userOutcome} onChange={(event) => patch('userOutcome', event.target.value)} className="hub-input mt-2" placeholder="Что пользователь сможет сделать после изменения?" /></label>
        <div className="mt-4 grid gap-4 md:grid-cols-2"><Lines label="В scope" hint="по одному пункту" value={lists.inScope} onChange={(value) => setLists((current) => ({ ...current, inScope: value }))} placeholder="Что именно делаем" /><Lines label="Вне scope" hint="обязательная граница" value={lists.outOfScope} onChange={(value) => setLists((current) => ({ ...current, outOfScope: value }))} placeholder="Что сознательно не делаем" /></div>
        <div className="mt-4 grid gap-4 md:grid-cols-2"><Lines label="Ограничения" hint="1–10" value={lists.constraints} onChange={(value) => setLists((current) => ({ ...current, constraints: value }))} placeholder="Offline first&#10;Не менять auth" /><Lines label="Критерии приёмки" hint="минимум 2" value={lists.acceptanceCriteria} onChange={(value) => setLists((current) => ({ ...current, acceptanceCriteria: value }))} placeholder="Проверяемый результат" /></div>
        <div className="mt-4 grid gap-4 md:grid-cols-2"><Lines label="Закрытые уточнения" hint="вопрос => ответ" value={lists.clarifications} onChange={(value) => setLists((current) => ({ ...current, clarifications: value }))} placeholder="Кто утверждает? => Владелец" /><Lines label="Evidence paths" hint="внутри repo" value={lists.evidencePaths} onChange={(value) => setLists((current) => ({ ...current, evidencePaths: value }))} placeholder="src/feature.ts&#10;src/feature.test.ts" /></div>
        <label className="mt-4 block text-sm text-gray-300">Как откатить изменение<textarea value={input.rollbackPlan} onChange={(event) => patch('rollbackPlan', event.target.value)} className="hub-input mt-2 min-h-24 resize-y" placeholder="Безопасный путь возврата без потери данных" /></label><button type="button" onClick={create} className="hub-btn mt-5 min-h-11 w-full sm:w-auto">Собрать спецификацию</button>{error && <div role="alert" className="mt-4 flex gap-2 rounded-lg border border-red-400/25 bg-red-400/5 p-3 text-sm text-red-300"><AlertTriangle size={16} />{error}</div>}
      </section>
      <aside className="hub-card h-fit p-5 xl:sticky xl:top-6"><h2 className="font-semibold text-white">Что получится</h2><ol className="mt-4 space-y-3">{Object.entries(LABELS).map(([id, label], index) => <li key={id} className="flex gap-3"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-xs ${id === 'implement' ? 'border-amber-400/30 text-amber-300' : 'border-hub-accent/30 text-hub-accent'}`}>{index + 1}</span><div><div className="text-sm font-medium text-gray-200">/{id} · {label}</div><p className="mt-0.5 text-xs leading-5 text-gray-500">{id === 'implement' ? 'Останется закрытой до независимого решения.' : 'Попадёт в versioned JSON.'}</p></div></li>)}</ol></aside>
    </div> : <><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><FileJson2 className="text-hub-accent" size={22} /><div><div className="font-semibold text-white">{artifact.input.projectName}</div><div className="text-xs text-gray-500">{artifact.schemaVersion} · {artifact.input.repository}</div></div></div><button type="button" onClick={reset} className="hub-btn-ghost min-h-11"><RotateCcw size={15} /> Начать заново</button></div>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-6"><div className="hub-card eclipse-card p-5 sm:p-6"><h2 className="font-semibold text-white">Шесть стадий</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{artifact.stages.map((item, index) => <article key={item.id} className="rounded-lg border border-hub-border bg-hub-surface p-4"><div className="flex items-center justify-between gap-3"><div className="text-sm font-semibold text-white">{index + 1}. {LABELS[item.id]}</div><code className="text-xs text-hub-accent">{item.command}</code></div><p className="mt-2 text-xs leading-5 text-gray-500">{item.summary}</p><div className={`mt-3 text-xs ${item.status === 'blocked' ? 'text-amber-300' : 'text-hub-success'}`}>{item.status === 'blocked' ? 'Заблокировано' : 'Готово'}</div></article>)}</div></div>
        <div className="hub-card p-5 sm:p-6"><h2 className="font-semibold text-white">Проверяемые задачи</h2><div className="mt-4 space-y-3">{artifact.tasks.map((task) => <div key={task.id} className="flex gap-3 rounded-lg border border-hub-border p-3"><span className="text-xs text-hub-accent">{task.id}</span><p className="text-sm text-gray-300">{task.acceptanceCriterion}</p></div>)}</div></div><div className="hub-card p-5 sm:p-6"><h2 className="font-semibold text-white">Offline evidence</h2><p className="mt-1 text-xs text-gray-500">Sentinel проверит пути без запуска команд и сети.</p><div className="mt-4 flex flex-wrap gap-2">{artifact.verification.evidencePaths.map((path) => <code key={path} className="rounded-md border border-hub-border bg-hub-surface px-2.5 py-1.5 text-xs text-gray-300">{path}</code>)}</div></div></section>
        <aside className="hub-card h-fit p-5 xl:sticky xl:top-6"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-hub-success" /><h2 className="font-semibold text-white">Утвердить спецификацию</h2></div><p className="mt-2 text-xs leading-5 text-gray-500">Approval разрешает импорт в Chat, но не выполнение кода.</p>{artifact.status === 'draft' ? <button type="button" onClick={() => run(() => markSpecGateReady(artifact))} className="hub-btn mt-5 min-h-11 w-full">Подготовить к проверке</button> : artifact.status === 'ready_for_review' ? <div className="mt-5 space-y-3">{([['scopeConfirmed', 'Scope и критерии точны'], ['risksConfirmed', 'Риски и запреты понятны'], ['rollbackConfirmed', 'План отката реалистичен']] as Array<[keyof SpecGateApprovalChecklist, string]>).map(([key, label]) => <label key={key} className="flex gap-3 rounded-lg border border-hub-border p-3 text-sm text-gray-300"><input type="checkbox" checked={checklist[key]} onChange={() => setChecklist((current) => ({ ...current, [key]: !current[key] }))} className="mt-0.5 h-4 w-4 accent-blue-500" />{label}</label>)}<button type="button" onClick={() => run(() => approveSpecGate(artifact, checklist))} className="hub-btn min-h-11 w-full">Утвердить для handoff</button></div> : <div className="mt-5 rounded-lg border border-hub-success/25 bg-hub-success/5 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-hub-success"><CheckCircle2 size={17} />Готово к review</div><button type="button" onClick={() => downloadArtifact(artifact)} className="hub-btn mt-4 min-h-11 w-full"><Download size={15} /> Скачать JSON</button></div>}{error && <div role="alert" className="mt-4 text-sm text-red-300">{error}</div>}</aside></div></>}
  </div></div>;
};
